### ISSUE TITLE
Upgrade to molecule v2

### ISSUE THREAD

**Issue by jperera** [idealista/jira-role#11]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Molecule v2 upgrade.

### Versions
1.0.2

### Additional Information

**Comment by jperera** [comment]
@dortegau do u think Docker driver is enough? Or maintaining Vagrant driver is interesting?

**Comment by jnogol** [comment]
IMO, Docker is enough
