### ISSUE TITLE
Unable to configure a MySQL DB as `jira_database_type`

### ISSUE THREAD

**Issue by mmolinac** [idealista/jira-role#4]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

The only available `jira_database_type` seems to be 'oracle'

### Steps to Reproduce

1. Check file https://github.com/idealista/jira-role/blob/master/templates/conf/dbconfig.xml.j2 and you can't see other choices covered. There are only an Oracle SSID string filled in.

**Expected behavior:** 

I was expecting a way to provide a different DB connection, for example, MySQL.

**Actual behavior:**

You can only provide Oracle DB access.

**Reproduces how often:**

Always.

### Versions

1.0.2

### Additional Information

No further information is needed to reproduce it.

**Comment by mmolinac** [comment]
Hi @jnogol .
Are you planning on update https://galaxy.ansible.com/idealista/jira-role to point to the latest release ?

**Comment by jnogol** [comment]
Hi @mmolinac,

just did it, forgot that this role in particular doesn't trigger an Ansible Galaxy update.

Thanks for your contribution, btw :)
